version: "3"

services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: youtube_api
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:alpine

  celery-beat:
    image: app:django
    container_name: celery-beat
    command: bash -c "sleep 2; celery -A youtube_api beat -l info"
    restart: on-failure
    depends_on:
      - redis
      - app
  celery:
    image: app:django
    container_name: celery
    volumes:
      - .:/django
    depends_on:
      - redis
      - celery-beat
    restart: on-failure
    command: bash -c "sleep 2; celery -A youtube_api worker -l info"
