# Generated by Django 3.2.6 on 2021-08-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('vid_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('published_at', models.DateTimeField()),
                ('thumbnailsUrls', models.URLField(max_length=1000)),
                ('channel_id', models.CharField(max_length=100)),
                ('channel_title', models.CharField(max_length=100)),
            ],
        ),
    ]
