# Generated by Django 3.2.6 on 2021-08-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='vid_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
